# 다층 퍼셉트론 - XOR - Tensorflow 1.x

In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [4]:
# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0]).reshape(4, 1)
x_data.shape, y_data.shape

((4, 2), (4, 1))

In [5]:
y_data

array([[0],
       [1],
       [1],
       [0]])

In [6]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [7]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [8]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

* reduce_mean() : 차원 축소

In [9]:
# Cost - Binary Cross Entropy
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [31]:
# Optimizer - Adam
lr = 0.03
# train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate=lr).minimize(cost)

In [32]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [33]:
# 학습
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data})
        
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    # weight, bias
    w1val, b1val, w2val, b2val = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{w1val} \nb1:\n{b1val} \nW2:\n{w2val} \nb2:\n{b2val}")

0 0.7033546
1000 0.69218135
2000 0.6916635
3000 0.69100124
4000 0.6901117
5000 0.6888426
6000 0.6869204
7000 0.6838564
8000 0.6787641
9000 0.67000216
10000 0.6544302

Hypothesis:
[[0.55852014]
 [0.52181387]
 [0.5184631 ]
 [0.3890158 ]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
0.75

W1:
[[ 1.4703913  -0.8070558 ]
 [ 1.4819714  -0.98675984]] 
b1:
[-2.8338425 -1.1841904] 
W2:
[[-1.8209642]
 [-0.9504501]] 
b2:
[0.5589528]
